# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [3]:
# resposta 1

class Circulo:
    def __init__(self, raio):
        self.raio = raio
    def area(self):
        return self.raio ** 2 * math.pi
    def perimetro(self):
        return  2 * math.pi * raio

## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    1 array
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    2 arrays
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [12]:
# resposta 2
import numpy as np

class Matematica:
    
    class Trigonometria:
        def __init__(self, arr):
            self.arr = arr
        
        def seno(self):
            return np.sin(self.arr)

        def coseno(self):
            return np.cos(self.arr)
        
        def tangente(self):
            return np.tan(self.arr)

        
    class Algebra:
        def __init__(self, arr1, arr2):
            self.arr1 = arr1
            self.arr2 = arr2
        
        def soma(self):
            return self.arr1 + self.arr2

        def subtracao(self):
            return self.arr1 - self.arr2
        
        def multiplicacao(self):
            return self.arr1 * self.arr2
        
        def divisao(self):
            return self.arr1 / self.arr2
            

trig = Matematica.Trigonometria(np.array([1, 1, 1]))
print(trig.seno())
print(trig.coseno())
print(trig.tangente())

alg = Matematica.Algebra(np.arr(1,1,1), )
            

[0.84147098 0.84147098 0.84147098]
[0.54030231 0.54030231 0.54030231]
[1.55740772 1.55740772 1.55740772]


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [45]:
# resposta 3

a = np.array([1,2,3])
b = np.array([3,4,5])

a = np.setdiff1d(a, b)
print(a)

[1 2]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre n e m do array recebido pela função

In [47]:
# resposta 4
def numbers_between(array, n, m):
    return array[(array > n) & (array < m)].copy()

numbers_between(np.arange(0, 10), 3, 6)

array([4, 5])

## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [49]:
# resposta 5
def diff_if_grather(array, n):
    return np.where((array > n), array - n, array).copy()

diff_if_grather(np.arange(0, 10), 6)


array([0, 1, 2, 3, 4, 5, 6, 1, 2, 3])

## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [50]:
# resposta 6
def order_by_axis(matrix, axis = 0):
    return np.sort(matrix, axis)


order_by_axis(np.array([[8,1,7], [4,3,9], [5,2,6]]), 1)

    

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])