In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
#sempre olhar o conjunto de dados com antenção
df_beer = pd.read_csv('./Consumo_cerveja.csv',nrows=365,delimiter=';')
df_beer.head()

Data  Temperatura Media (C)  Temperatura Minima (C)  \
0  01/01/2015                  27.30                    23.9   
1  02/01/2015                  27.02                    24.5   
2  03/01/2015                  24.82                    22.4   
3  04/01/2015                  23.98                    21.5   
4  05/01/2015                  23.82                    21.0   

   Temperatura Maxima (C)  Precipitacao (mm)  Final de Semana  \
0                    32.5                0.0                0   
1                    33.5                0.0                0   
2                    29.9                0.0                1   
3                    28.6                1.2                1   
4                    28.3                0.0                0   

   Consumo de cerveja (litros)  
0                       25.461  
1                       28.972  
2                       30.814  
3                       29.799  
4                       28.900

In [3]:
#tratamento do data frame
df_beer = df_beer.rename(columns={'Temperatura Media (C)':'meanTemp','Temperatura Minima (C)':'minTemp','Temperatura Maxima (C)':'maxTemp',
                       'Precipitacao (mm)':'precip','Final de Semana':'weekend','Consumo de cerveja (litros)':'consumo'})
df_beer.head()

Data  meanTemp  minTemp  maxTemp  precip  weekend  consumo
0  01/01/2015     27.30     23.9     32.5     0.0        0   25.461
1  02/01/2015     27.02     24.5     33.5     0.0        0   28.972
2  03/01/2015     24.82     22.4     29.9     0.0        1   30.814
3  04/01/2015     23.98     21.5     28.6     1.2        1   29.799
4  05/01/2015     23.82     21.0     28.3     0.0        0   28.900

In [4]:
feature_col = ['maxTemp','precip','weekend']
meta_col = ['consumo']

X = df_beer[feature_col].values
y = df_beer[meta_col].values
split_test_size = 0.30

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split_test_size, random_state=42)

In [6]:
lr_model = linear_model.LinearRegression()
lr_model.fit(X_train, y_train.ravel()) # flatten arrays

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
y_pred = lr_model.predict(X_test)

In [8]:
mean_squared_error(y_test,y_pred)

5.4808534596126615

In [9]:
#testando com novas amostras
pred_value = [[35,0,1]]
lr_model.predict(pred_value)

array([35.09452079])

In [10]:
lr_model.coef_

array([ 0.66752499, -0.05305718,  5.33497184])

In [14]:
#computando parâmetros analiticamente
X = np.matrix(X)
aux1 = np.matmul(X.transpose(),X)
inv = np.linalg.inv(aux1)
aux2 = np.matmul(X.transpose(),y)
theta = np.matmul(inv,aux2)
theta

matrix([[ 0.89911459],
        [-0.04817406],
        [ 5.49500367]])

In [15]:
from sklearn.externals import joblib

joblib.dump(lr_model, r'./lr_model.pkl') 
lr_model_loaded = joblib.load(r'./lr_model.pkl') 